baseURL = 'https://TriangleMesh.github.io/'
languageCode = 'en-us'
title = 'Qingyun Qian'
theme = 'hugo-ivy'

hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    posts = "/posts/:year/:month/:day/:slug/"

# [[menu.main]]
#     name = "Project"
#     url = "/project/"
#     weight = 1
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "Leetcode"
    url = "/leetcode/"
    weight = 2

# [[menu.main]]
#     name = "Categories"
#     url = "/categories/"
#     weight = 3
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 4
# [[menu.main]]
#     name = "About"
#     url = "/about/"
#     weight = 3
    


[params]
  # description abou this website
  description = "Undergrad at UBC CS<br>Research Assistant in the UBC NLP Group"
  footer = "&copy; <a href='https://TriangleMesh.github.io/'>Qingyun Qian</a> | <a href='https://github.com/TriangleMesh'>Github</a> | <a href='mailto:trianglemeshq@gmail.com'>Email</a> | <a href='https://scholar.google.com/citations?user=g8avwkcAAAAJ&amp;hl=en'>Google Scholar</a> | <a href='https://www.linkedin.com/in/qingyun-q-669985208/'>LinkedIn</a> | since 2024"

  # highlightjsCDN = "//cdn.bootcss.com"
  # highlightjsLang = ["r", "yaml", "tex"]
  # highlightjsTheme = "github"
  # highlightjsVersion = "9.12.0"


## TBD
[params.twikoo]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = true
style = "colorful"
lineNos = true
lineNumbersInTable = true
noClasses = true
tabWidth = 4
guessSyntax = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
startLevel = 1

